apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: subscriber-api-prod
resources:
  - ../../base
patches:
  - path: replicas-patch.yaml
images:
  - name: image-registry.openshift-image-registry.svc:5000/mod10-demos/subscriber-api
    newTag: v3
